### ISSUE TITLE
دیتابیس

### ISSUE THREAD

**Issue by peyman1959** [ham3da/moein-dictionary-free#2]
سلام
ببخشید از چه دیتابیسی استفاده میکنید و آیا دیتا بیستون هم متن بازه؟ میتونم تو پروژه خودم ازش استفاده کنم؟

**Comment by ham3da** [comment]
سلام. دیتابیس MySQL. بله باز هست.

**Comment by ham3da** [comment]
سلام. دیتابیس MySQL. بله باز هست.
